# Generated by Django 2.2.6 on 2019-10-29 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('entregado', models.BooleanField()),
                ('pagado', models.BooleanField()),
                ('descuento', models.FloatField()),
            ],
            options={
                'verbose_name': 'Cabecera de Pedido',
                'verbose_name_plural': 'Cabeceras de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Lista de Categorias',
            },
        ),
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Lista de Marcas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Lista de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Lista de Zonas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Codigo.Usuario')),
                ('puntaje', models.FloatField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('verificado', models.BooleanField()),
                ('idZona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Zona')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Lista de Clientes',
            },
            bases=('Codigo.usuario',),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Codigo.Usuario')),
                ('fecha_inicio', models.DateField()),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
            bases=('Codigo.usuario',),
        ),
        migrations.CreateModel(
            name='ZonaCoordenada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCoordenadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Coordenada')),
                ('idZona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Zona')),
            ],
            options={
                'verbose_name': 'Coordenadas de una zona',
                'verbose_name_plural': 'Asignacion de Coordenadas a Zonas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('presentacion', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Categoria')),
                ('idMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Lista de Productos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('idCabeceraPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.CabeceraPedido')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Producto')),
            ],
            options={
                'verbose_name': 'Detalle Pedido',
                'verbose_name_plural': 'Detalles Pedidos',
            },
        ),
        migrations.AddField(
            model_name='cabecerapedido',
            name='idFormaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.FormaPago'),
        ),
        migrations.CreateModel(
            name='ZonaTrabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('idZona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Zona')),
                ('idTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Trabajador')),
            ],
            options={
                'verbose_name': 'Zona Asignada',
                'verbose_name_plural': 'Zonas Asignadas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha_pago', models.DateField()),
                ('idCabeceraPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.CabeceraPedido')),
                ('idTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Trabajador')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas de Producto',
            },
        ),
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=200)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Cliente')),
            ],
            options={
                'verbose_name': 'Datos de Facturacion',
                'verbose_name_plural': 'Datos de Facturacion',
            },
        ),
        migrations.AddField(
            model_name='cabecerapedido',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Cliente'),
        ),
        migrations.AddField(
            model_name='cabecerapedido',
            name='idTrabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Trabajador'),
        ),
    ]
