# Generated by Django 2.2.6 on 2019-10-29 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Codigo', '0002_marca_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('entregado', models.BooleanField()),
                ('pagado', models.BooleanField()),
                ('descuento', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('verificado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=200)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('idCabeceraPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.CabeceraPedido')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha_pago', models.DateField()),
                ('idCabeceraPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.CabeceraPedido')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('presentacion', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Categorias')),
                ('idMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Marcas')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ZonasCoordenadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCoordenadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Coordenadas')),
                ('idZona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Zona')),
            ],
        ),
        migrations.CreateModel(
            name='ZonasTrabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('idTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Trabajador')),
                ('idZona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Zona')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contacto',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(default=1, max_length=8, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Usuario'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='idTrabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Trabajador'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Productos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idZona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Zona'),
        ),
        migrations.AddField(
            model_name='cabecerapedido',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Cliente'),
        ),
        migrations.AddField(
            model_name='cabecerapedido',
            name='idFormaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.FormaPago'),
        ),
        migrations.AddField(
            model_name='cabecerapedido',
            name='idTrabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codigo.Trabajador'),
        ),
    ]
