# Generated by Django 2.2.6 on 2019-11-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Codigo', '0003_auto_20191113_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabecerapedido',
            old_name='idCliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='cabecerapedido',
            old_name='idFormaPago',
            new_name='formaPago',
        ),
        migrations.RenameField(
            model_name='cabecerapedido',
            old_name='idTrabajador',
            new_name='trabajador',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='idZona',
            new_name='zona',
        ),
        migrations.RenameField(
            model_name='coordenada',
            old_name='idZona',
            new_name='zona',
        ),
        migrations.RenameField(
            model_name='datosfacturacion',
            old_name='idCliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='idCabeceraPedido',
            new_name='cabeceraPedido',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='idProducto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='idCabeceraPedido',
            new_name='cabeceraPedido',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='idTrabajador',
            new_name='trabajador',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='idCategoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='idMarca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='zonatrabajador',
            old_name='idTrabajador',
            new_name='trabajador',
        ),
        migrations.RenameField(
            model_name='zonatrabajador',
            old_name='idZona',
            new_name='zona',
        ),
    ]
