# Generated by Django 2.2.6 on 2019-11-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codigo', '0004_auto_20191113_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenada',
            name='orden_polygono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
