# Generated by Django 2.2.6 on 2019-11-15 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Codigo', '0005_coordenada_orden_polygono'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='foto_perfil',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosfacturacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_facturacion', to='Codigo.Cliente'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cabeceraPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedido', to='Codigo.CabeceraPedido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='Codigo.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='Codigo.Marca'),
        ),
    ]
