# Generated by Django 2.2.6 on 2019-11-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codigo', '0006_auto_20191114_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='contrasenia',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='usuario',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
